swagger: '2.0'
info:
  version: '0.6'
  title: Storage Inventory files service (minoc)
  description: |
    This service allows authorised users to read, write, update (metadata), and delete files. Pre-authorised URLs may be constructed by trusted services by including a signed pre-auth token in the path element before the Artifact URI.
basePath: '/minoc'
schemes:
  - https
paths:
  '/files/{Artifact.uri}':
    parameters:
    - name: Artifact.uri
      in: path
      type: string
      description: The artifact URI
      required: true
    get:
      description: |
        Download the file identified by parameter Artifact.uri, optionally cutting a subset of a FITS file.
      tags:
        - Artifact transfer
      summary: Download a file
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Successful response.
          headers:
            Content-Disposition:
              description: Contains suggested filename
              type: string
            Content-Encoding:
              description: The content encoding of the file
              type: string
            Content-Type:
              description: The content type of the file
              type: string
            Digest:
              description: The content checksum (MD5) of the file
              type: string
            Content-Length:
              description: The length of the file in bytes (not set if SUB used)
              type: string
            Last-Modified:
              description: Timestamp when data was modified (not set if SUB used)
              type: date
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed
        '403':
          description: If the client does not have permission
        '404':
          description: If the artifact could not be found
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: SUB
          in: query
          description: 'SUB-region of a FITS file image.  Multiple SUB parameters are allowed and will generate MEF output in file order. Examples: entire extensions (SUB=[1]&SUB=[SCI,2]), or more general purpose (SUB=[SCI,3][400:500]).'
          required: false
          type: string
          collectionFormat: multi
        - name: POS
          in: query
          description: The positional regions to be extracted from the data.
          required: false
          type: string
        - name: CIRCLE
          in: query
          description: The spatial region using the CIRCLE xtype defined in DALI.
          required: false
          type: string
        - name: POLYGON
          in: query
          description: The spatial region using the POLYGON xtype defined in DALI.
          required: false
          type: string
        - name: BAND
          in: query
          description: The wavelength interval(s) using the INTERVAL xtype defined in DALI.
          required: false
          type: string
        - name: TIME
          in: query
          description: The time interval(s) using the INTERVAL xtype defined in DALI.
          required: false
          type: string
        - name: POL
          in: query
          type: array
          collectionFormat: multi
          items:
            type: string
          description: The polarization state(s) (Stokes), supports multiple values.
          required: false
        - name: META
          in: query
          description: 'extract metadata (headers) from a file. A single parameter META=true is supported for FITS files. Output will be a plain text rendition of the headers.'
          required: false
          type: boolean
    put:
      description: |
        Upload a file identified by parameter Artifact.uri
      tags:
        - Artifact transfer
      summary: Upload a file
      schemes:
        - https
      consumes:
        - application/octet-stream
      responses:
        '201':
          description: created - upload successful or transaction committed
          headers:
            Content-MD5:
              description: The MD5 checksum of the file
              type: string
            Content-Length:
              description: The length of the file in bytes
              type: string
        '202':
          description: accepted - transaction started
          headers:
            X-Put-Txn:
              description: transactionID
              type: string
            Content-Length:
              description: The length of the file in bytes
              type: string
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed
        '403':
          description: If the client does not have permission
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: Content-Type
          in: header
          type: string
          description: The content type of the file
          required: false
        - name: Digest
          in: header
          type: string
          description: The content checksum (MD5) of the file
          required: false
        - name: Content-Length
          in: header
          type: string
          description: The number of bytes to be uploaded
          required: false
        - name: X-Put-Txn
          in: header
          type: string
          description: |
            "true" to start a new transaction; a transactionID to append to an existing transaction
          required: false
    head:
      description: |
        Get the metadata for the file identified by Artifact.uri
      tags:
        - Artifact management
      summary: View file metadata
      schemes:
        - https
      responses:
        '200':
          description: Successful response
          headers:
            Content-Disposition:
              description: 'The content-disposition with suggested filename (normally last path element in artifact URI)'
              type: string
            Content-Type:
              description: The content type of the file
              type: string
            Digest:
              description: The content checksum (MD5) of the file
              type: string
            Content-Length:
              description: The length of the file in bytes
              type: string
            Last-Modified:
              description: Timestamp when data was modified
              type: date
            X-Put-Txn:
              description: transactionID
              type: string
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed
        '403':
          description: If the client does not have permission
        '404':
          description: If the artifact could not be found
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: X-Put-Txn
          in: header
          type: string
          description: transactionID to check state of an existing transaction
          required: false
    delete:
      description: |
        Delete the file identified by parameter Artifact.uri
      tags:
        - Artifact management
      summary: Delete a file
      schemes:
        - https
      responses:
        '204':
          description: Successful response 
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed
        '403':
          description: If the client does not have permission
        '404':
          description: If the artifact could not be found
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: X-Put-Txn
          in: header
          type: string
          description: transactionID to abort
          required: false
    post:
      description: |
        Set the metadata values for an file
      tags:
        - Artifact management
      summary: Update file metadata
      schemes:
        - https
      parameters:
        - name: contentType
          in: query
          type: string
          description: The new content type of the file
          required: false
        - name: contentEncoding
          in: query
          type: string
          description: The new content encoding of the file
          required: false
      responses:
        '200':
          description: Successful response
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
  '/files/{auth-token}/{artifact-uri}':
    parameters:
    - name: auth-token
      in: path
      type: string
      description: An authorization token
      required: true
    - name: artifact-uri
      in: path
      type: string
      description: The artifact URI
      required: true
    get:
      description: |
        Download the file identified by parameter artifact-uri.
      tags:
        - Artifact transfer
      summary: Download a file
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Successful response.
          headers:
            Content-Disposition:
              description: 'The content-disposition with suggested filename (normally last path element in artifact URI)'
              type: string
            Content-Type:
              description: The content type of the file
              type: string
            Digest:
              description: The content checksum (MD5) of the file
              type: string
            Content-Encoding:
              description: The content encoding of the file
              type: string
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: SUB
          in: query
          description: 'Sub-region of a FITS file image.  Multiple SUB parameters are allowed and will generate MEF output in file order. Examples: entire extensions (SUB=[1]&SUB=[SCI,2]), or more general purpose (SUB=[SCI,3][400:500]).'
          required: false
          type: string
          collectionFormat: multi
        - name: POS
          in: query
          description: The positional regions to be extracted from the data.
          required: false
          type: string
        - name: CIRCLE
          in: query
          description: The spatial region using the CIRCLE xtype defined in DALI.
          required: false
          type: string
        - name: POLYGON
          in: query
          description: The spatial region using the POLYGON xtype defined in DALI.
          required: false
          type: string
        - name: BAND
          in: query
          description: The wavelength interval(s) using the INTERVAL xtype defined in DALI.
          required: false
          type: string
        - name: TIME
          in: query
          description: The time interval(s) using the INTERVAL xtype defined in DALI.
          required: false
          type: string
        - name: POL
          in: query
          type: array
          collectionFormat: multi
          items:
            type: string
          description: The polarization state(s) (Stokes), supports multiple values.
          required: false
        - name: META
          in: query
          description: 'extract metadata (headers) from a file. A single parameter META=true is supported for FITS files. Output will be a plain text rendition of the headers.'
          required: false
          type: boolean
    put:
      description: |
        Upload a file identified by parameter artifact-uri.
      tags:
        - Artifact transfer
      summary: Upload a file
      schemes:
        - https
      consumes:
        - application/octet-stream
      responses:
        '201':
          description: Successful response
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: Content-Type
          in: header
          type: string
          description: The content type of the file
          required: false
        - name: Digest
          in: header
          type: string
          description: The content checksum (MD5) of the file
          required: false
        - name: Content-Length
          in: header
          type: string
          description: The content length of the file
          required: false
    head:
      description: |
        Get the metadata for the file identified by parameter artifact-uri.
      tags:
        - Artifact management
      summary: View file metadata
      schemes:
        - https
      responses:
        '200':
          description: Successful response
          headers:
            Content-Disposition:
              description: 'The content-disposition with suggested filename (normally last path element in artifact URI)'
              type: string
            Content-Type:
              description: The content type of the file
              type: string
            Digest:
              description: The content checksum (MD5) of the artifact
              type: string
            Content-Length:
              description: The length of the file in bytes
              type: string
            Last-Modified:
              description: Timestamp when data was modified
              type: date
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed
        '403':
          description: If the client does not have permission
        '404':
          description: If the artifact could not be found
        '500':
          description: Internal error
        '503':
          description: Service busy
  /availability:
    get:
      tags:
        - Support Interfaces
      summary: VOSI Availability
      description: 'Indicates whether the service is operable and shows the reliability of the service for extended and scheduled requests. If the query parameter ''detail=min'' is used, a light weight heart beat test will be performed. The heart beat test returns status 200 if the service is available.'
      parameters:
        - name: detail
          in: query
          description: 'Specifies heart beat to be used to check for availability of this service, the value ''min'' must be used, otherwise the full availability test will be performed'
          required: false
          type: string
      responses:
        '200':
          description: A VOSI availability document in XML.
  /capabilities:
    get:
      summary: VOSI Capabilities
      tags:
        - Support Interfaces
      description: |
        Provides the service metadata in the form of a list of Capability descriptions.  Each of these descriptions is an XML element that:
        <ul>
        <li>states that the service provides a particular, IVOA-standard function;</li>
        <li>lists the interfaces for invoking that function;</li>
        <li>records any details of the implementation of the function that are not defined as default or constant in the standard for that function.</li>
        </ul>
      responses:
        '200':
          description: A VOSI Capabilities document in XML.
        '500':
          description: Internal server error
        '503':
          description: Service too busy
