swagger: '2.0'
info:
  version: '0.6'
  title: Artifact storage and management service (minoc)
  description: 'A programmatic interface for storing, retrieving and managing artifacts at a storage site.<br/><br/>Clients may authenticate to this service in one of three ways:<br/>1.  By supplying an authentication token and using it as the auth-token parameter in the path.  URLs containing auth-tokens can be retrieved from the global locate service.<br/>2.  By providing a cookie in the Cookie header<br/>3.  By using a client certificate over SSL.'
basePath: '/minoc'

paths:
  '/files/{artifact-uri}':
    parameters:
    - name: artifact-uri
      in: path
      type: string
      description: The artifact URI
      required: true
    get:
      description: |
        Download the file identified by parameter artifact-uri, optionally cutting a subset of a FITS file.
      tags:
        - Artifact transfer
      summary: Download a file
      schemes:
        - https
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Successful response.
          headers:
            Content-Disposition:
              description: 'The content-disposition with suggested filename (normally last path element in artifact URI)'
              type: string
            Content-Type:
              description: The content type of the file
              type: string
            Content-MD5:
              description: The content MD5 of the file
              type: string
            Content-Length:
              description: The content length of the file
              type: string
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
       - name: SUB
         in: query
         description: 'SUB-region of a FITS file image.  Multiple SUB parameters are allowed and will generate MEF output in file order. Examples: entire extensions (SUB=[1]&SUB=[SCI,2]), or more general purpose (SUB=[SCI,3][400:500]).'
         required: false
         type: string
         collectionFormat: multi
       - name: META
         in: query
         description: 'extract METAdata (headers) from a file. A single parameter META=true is supported for FITS files. Output will be a plain text rendition of the headers.'
         required: false
         type: boolean
    put:
      description: |
        Upload a file identified by parameter artifact-uri.
      tags:
        - Artifact transfer
      summary: Upload a file
      schemes:
        - https
      consumes:
        - application/octet-stream
      responses:
        '201':
          description: Successful response
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: Content-Type
          in: header
          type: string
          description: The content type of the file
          required: false
        - name: Content-MD5
          in: header
          type: string
          description: The content MD5 of the file
          required: false
        - name: Content-Length
          in: header
          type: string
          description: The content length of the file
          required: false
    head:
      description: |
        Get the metadata for the file identified by parameter artifact-uri.
      tags:
        - Artifact management
      summary: View file metadata
      schemes:
        - https
      responses:
        '200':
          description: Successful response
          headers:
            Content-Type:
              description: The content type of the file
              type: string
            Content-MD5:
              description: The content MD5 of the file
              type: string
            Content-Length:
              description: The content length of the file
              type: string
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
    delete:
      description: |
        Delete the file identified by parameter artifact-uri.
      tags:
        - Artifact management
      summary: Delete a file
      schemes:
        - https
      responses:
        '200':
          description: Successful response 
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
    post:
      description: |
        Set the metadata values for an file
      tags:
        - Artifact management
      summary: Update the metadata of the file identified by parameter artifct-uri.
      schemes:
        - https
      parameters:
        - name: uri
          in: query
          type: string
          description: The new URI for the file
          required: false
        - name: contentType
          in: query
          type: string
          description: The new content type of the file
          required: false
        - name: contentEncoding
          in: query
          type: string
          description: The new content encoding of the file
          required: false
      responses:
        '200':
          description: Successful response
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
  '/files/{auth-token}/{artifact-uri}':
    parameters:
    - name: auth-token
      in: path
      type: string
      description: An authorization token
      required: true
    - name: artifact-uri
      in: path
      type: string
      description: The artifact URI
      required: true
    get:
      description: |
        Download the file identified by parameter artifact-uri.
      tags:
        - Artifact transfer
      summary: Download a file
      schemes:
        - https
      produces:
        - application/octet-stream
      responses:
        '200':
          description: Successful response.
          headers:
            Content-Disposition:
              description: 'The content-disposition of the file in the form<br/><br/>Content-Disposition\: inline; filename=\"\<name\>\"<br/><br/>where \<name\> is the last path segment of the URI of the artifact.'
              type: string
            Content-Type:
              description: The content type of the file
              type: string
            Content-MD5:
              description: The content MD5 of the file
              type: string
            Content-Length:
              description: The content length of the file
              type: string
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: SUB
          in: query
          description: 'Sub-region of a FITS file image.  Multiple SUB parameters are allowed and will generate MEF output in file order. Examples: entire extensions (SUB=[1]&SUB=[SCI,2]), or more general purpose (SUB=[SCI,3][400:500]).'
          required: false
          type: string
          collectionFormat: multi
    put:
      description: |
        Upload a file identified by parameter artifact-uri.
      tags:
        - Artifact transfer
      summary: Upload a file
      schemes:
        - https
      consumes:
        - application/octet-stream
      responses:
        '201':
          description: Successful response
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '500':
          description: Internal error
        '503':
          description: Service busy
      parameters:
        - name: Content-Type
          in: header
          type: string
          description: The content type of the file
          required: false
        - name: Content-MD5
          in: header
          type: string
          description: The content MD5 of the file
          required: false
        - name: Content-Length
          in: header
          type: string
          description: The content length of the file
          required: false
    head:
      description: |
        Get the metadata for the file identified by parameter artifact-uri.
      tags:
        - Artifact management
      summary: View file metadata
      schemes:
        - https
      responses:
        '200':
          description: Successful response
          headers:
            Content-Type:
              description: The content type of the artifact
              type: string
            Content-MD5:
              description: The content MD5 of the artifact
              type: string
            Content-Length:
              description: The content length of the artifact
              type: string
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
    delete:
      description: |
        Delete the file identified by parameter artifact-uri.
      tags:
        - Artifact management
      summary: Delete a file
      schemes:
        - https
      responses:
        '200':
          description: Successful response 
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
    post:
      description: |
        Set the metadata values for a file
      tags:
        - Artifact management
      summary: Update the metadata of the file identified by parameter artifact-uri.
      schemes:
        - https
      parameters:
        - name: uri
          in: query
          type: string
          description: The new URI for the file
          required: false
        - name: contentType
          in: query
          type: string
          description: The new content type of the file
          required: false
        - name: contentEncoding
          in: query
          type: string
          description: The new content encoding of the file
          required: false
      responses:
        '200':
          description: Successful response
        '401':
          description: If the client does not provide credentials and anonymous access is disallowed.
        '403':
          description: If the client does not have permission.
        '404':
          description: If the artifact could not be found.
        '500':
          description: Internal error
        '503':
          description: Service busy
  /availability:
    get:
      tags:
        - Support Interfaces
      summary: VOSI Availability
      description: 'Indicates whether the service is operable and shows the reliability of the service for extended and scheduled requests. If the query parameter ''detail=min'' is used, a light weight heart beat test will be performed. The heart beat test returns status 200 if the service is available.'
      parameters:
        - name: detail
          in: query
          description: 'Specifies heart beat to be used to check for availability of this service, the value ''min'' must be used, otherwise the full availability test will be performed'
          required: false
          type: string
      responses:
        '200':
          description: A VOSI availability document in XML.
  /capabilities:
    get:
      summary: VOSI Capabilities
      tags:
        - Support Interfaces
      description: |
        Provides the service metadata in the form of a list of Capability descriptions.  Each of these descriptions is an XML element that:
        <ul>
        <li>states that the service provides a particular, IVOA-standard function;</li>
        <li>lists the interfaces for invoking that function;</li>
        <li>records any details of the implementation of the function that are not defined as default or constant in the standard for that function.</li>
        </ul>
      responses:
        '200':
          description: A VOSI Capabilities document in XML.
        '500':
          description: Internal server error
        '503':
          description: Service too busy
